plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_name}-neoforge-${minecraft_version}"
}

repositories {
    mavenCentral()
    flatDir { dirs 'libs' }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            gameDirectory = file('run/client')
        }
        server {
            server()
            gameDirectory = file('run/server')
            programArgument '--nogui'
        }
        data {
            clientData()
            gameDirectory = file('run/data')
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources').absolutePath, '--existing', file('src/main/resources').absolutePath
        }
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}


sourceSets.main.java.setSrcDirs(['src/port/java'])
sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.withType(ProcessResources).configureEach {
    def properties = [
            minecraft_version_range: minecraft_version_range,
            neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties properties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand properties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
    options.compilerArgs += ['-Xmaxerrs', '1000']
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}


