org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.59
neo_version_range=[26.2.0.59,)
loader_version_range=[4,)

mod_id=hamsters
mod_name=Hamsters
mod_license=MIT
mod_version=26.2-1.2.0-youer
mod_group_id=com.starfish_studios.hamsters
mod_authors=Starfish Studios, Ninnih, Yoake
mod_description=Adds tameable hamsters, hamster care blocks and biome-aware natural spawning for NeoForge 26.2 and Youer.
